version: '3'
services:
  app:
    build: .
    container_name: open_tech_pay_app
    ports:
     - "5000:5000"
     - "5001:5001"
    volumes:
     - ./:/app
  db:
    container_name: open_tech_pay_db
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     - MYSQL_DATABASE=open_tech_pay
    volumes:
     - "${HOST_SQL_STORAGE_PATH}:/var/lib/mysql"
